# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c515e0ff9ee25840e5dc582b4028eee76ef2a268db914d3a23e9bf721133d69144d56342b1b5b23fbd3822c669701df1777470cf7732b83d0ec2d3e54d2fc961

test:
  secret_key_base: c1d74878045f344d71b6bc8bff82a7b350ab492f83c767b0dce0dc1accfa8493016e27b14ec6855328fdfdb25162463b83b6b97fcb23700f3b7e15453a113da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
